
server:
  port: 8086

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
  application:
    name: eureka-service-consumer-feign

eureka:
  client:
    serviceUrl:
      #      指定服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/

#启用hystrix
feign:
  hystrix:
    enabled: true
