server:
  port: 8088

spring:
  application:
    name: client

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info
#  endpoint:
#    health:
#      show-details: always
#  server: # 指定actuator端口。如果不指定则与系统服务端口一致。建议修改
#    port: 8888






