#server:
#  port: 8861
eureka:
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
# 服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: eureka-client-provider